/* THIS FILE WAS MODIFIED TO FIX CSS CONFLICTS AND HYDRATION WARNINGS */
/* Original was auto-generated by Payload - customized for better UX */
import config from '@payload-config'
import '@payloadcms/next/css'
// NOTE: Do NOT import globals.css here - it conflicts with Payload's admin styles
// The marketing site has its own globals.css in (marketing)/layout.tsx
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import React from 'react'

import { importMap } from './admin/importMap'
import { SuppressHydrationWarning } from './suppress-hydration-warning'

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

/**
 * Payload Admin Layout
 *
 * Custom wrapper to fix:
 * - CSS conflicts (removed globals.css)
 * - Hydration warnings from browser extensions
 */
const Layout = ({ children }: Args) => {
  // We need to suppress hydration warnings caused by browser extensions (Grammarly, etc.)
  // Payload's RootLayout sets suppressHydrationWarning={false} by default
  // The SuppressHydrationWarning component filters console errors
  return (
    <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
      <SuppressHydrationWarning />
      {children}
    </RootLayout>
  )
}

export default Layout
