version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: goodopalco-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: goodopalco
      POSTGRES_PASSWORD: goodopalcopass
      POSTGRES_DB: goodopalco
    ports:
      - '5432:5432'
    volumes:
      - goodopalco-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U goodopalco']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  goodopalco-db-data:
    name: goodopalco-db-data
