/**
 * Central type exports for the Rapid Sites application
 * Import types from here to maintain consistency
 */

// Common types
export type {
  Address,
  ApiError,
  ApiResponse,
  ArrayElement,
  AuditTrail,
  Awaited,
  ContactInfo,
  DeepPartial,
  DeepRequired,
  FormField,
  ID,
  Image,
  KeysOfType,
  Link,
  Nullable,
  Optional,
  OptionalKeys,
  PaginatedResponse,
  PaginationParams,
  RequireKeys,
  Result,
  SEO,
  Slug,
  SocialLinks,
  SoftDelete,
  Status,
  Timestamps,
  ValidationError,
  Visibility,
} from './common'

// Site types
export type {
  Author,
  BlogPost,
  Category,
  ContactSubmission,
  FAQ,
  GalleryImage,
  MenuItem,
  NavigationMenu,
  Page,
  PageContent,
  PageSection,
  PageStatus,
  PageType,
  PricingFeature,
  PricingPlan,
  SectionType,
  Service,
  Tag,
  TeamMember,
  Testimonial,
} from './site'

// Component types
export type {
  BaseComponentProps,
  BreadcrumbItem,
  BreadcrumbsProps,
  ButtonProps,
  ButtonVariant,
  CTASectionData,
  CardProps,
  CardVariant,
  ColorVariant,
  ContainerProps,
  DropdownProps,
  EmptyStateProps,
  ErrorStateProps,
  Feature,
  FeaturesSectionData,
  FooterLinkGroup,
  FooterProps,
  HeroSectionData,
  InputProps,
  InputVariant,
  LoadingProps,
  ModalProps,
  NavItem,
  NavigationProps,
  SectionProps,
  Size,
  SocialLink,
  Stat,
  StatsSectionData,
  TabItem,
  TabsProps,
  TestableComponent,
} from './component'
