/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    categories: Category;
    tags: Tag;
    posts: Post;
    products: Product;
    orders: Order;
    customers: Customer;
    enquiries: Enquiry;
    courses: Course;
    'commerce-import-runs': CommerceImportRun;
    'inventory-reservations': InventoryReservation;
    'custom-quotes': CustomQuote;
    'custom-quote-events': CustomQuoteEvent;
    'ring-designs': RingDesign;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    'commerce-import-runs': CommerceImportRunsSelect<false> | CommerceImportRunsSelect<true>;
    'inventory-reservations': InventoryReservationsSelect<false> | InventoryReservationsSelect<true>;
    'custom-quotes': CustomQuotesSelect<false> | CustomQuotesSelect<true>;
    'custom-quote-events': CustomQuoteEventsSelect<false> | CustomQuoteEventsSelect<true>;
    'ring-designs': RingDesignsSelect<false> | RingDesignsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'user';
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Stable attachment ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  /**
   * Original URL for a safely imported legacy asset
   */
  legacySourceUrl?: string | null;
  alt: string;
  caption?: string | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  /**
   * Stable public author ID from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  name: string;
  slug: string;
  bio?: string | null;
  avatar?: (number | null) | Media;
  tenantId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Stable category ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * Stable tag ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  name: string;
  slug: string;
  description?: string | null;
  tenantId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Stable post ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short summary of the post
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  /**
   * When this post was published
   */
  publishedAt?: string | null;
  author: number | Author;
  categories: (number | Category)[];
  tags?: (number | Tag)[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string[] | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  price: number;
  /**
   * Original price (for showing discounts)
   */
  compareAtPrice?: number | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  category: 'opal-rings' | 'opal-necklaces' | 'opal-earrings' | 'opal-bracelets' | 'raw-opals' | 'custom-commissions';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  featured?: boolean | null;
  /**
   * Available quantity (0 = out of stock)
   */
  stock?: number | null;
  /**
   * Stock Keeping Unit (unique identifier)
   */
  sku?: string | null;
  /**
   * Original WooCommerce product ID
   */
  legacyWooId?: number | null;
  /**
   * Original WooCommerce product status
   */
  wooStatus?: string | null;
  wooCatalogVisibility?: string | null;
  wooManageStock?: boolean | null;
  wooModifiedAt?: string | null;
  /**
   * Metal type used in the jewelry
   */
  material?: ('sterling-silver' | '14k-gold' | '18k-gold' | 'white-gold' | 'rose-gold' | 'platinum' | 'none') | null;
  /**
   * Type of opal used
   */
  stoneType?:
    | ('black-opal' | 'white-opal' | 'boulder-opal' | 'crystal-opal' | 'fire-opal' | 'matrix-opal' | 'opal-doublet')
    | null;
  /**
   * Australian mine location where opal was sourced
   */
  stoneOrigin?:
    | ('lightning-ridge' | 'coober-pedy' | 'mintabie' | 'andamooka' | 'queensland' | 'other-australian')
    | null;
  dimensions?: {
    /**
     * Length in mm
     */
    length?: number | null;
    /**
     * Width in mm
     */
    width?: number | null;
    /**
     * Depth/height in mm
     */
    depth?: number | null;
  };
  /**
   * Weight in carats (for opals) or grams (for jewelry)
   */
  weight?: number | null;
  /**
   * Required before displaying weight on finished jewellery
   */
  weightUnit?: ('carats' | 'grams') | null;
  /**
   * Review inferred values below. Use Manual when you intentionally override them.
   */
  builderMappingStatus?: ('pending' | 'reviewed' | 'manual' | 'stale') | null;
  /**
   * Deterministic input completeness score; not image-recognition accuracy.
   */
  builderMappingConfidence?: number | null;
  /**
   * Inference rules version. Version changes make approved mappings stale.
   */
  builderMappingVersion?: number | null;
  /**
   * Manual mappings remain protected when product images change.
   */
  builderMappingMode?: ('inferred' | 'manual') | null;
  /**
   * Changes whenever mapped source image identity or order changes.
   */
  builderMappingSourceImageHash?: string | null;
  /**
   * Tracks source image, name, opal type, slug, and dimensions.
   */
  builderMappingInputHash?: string | null;
  /**
   * Zero-based gallery image used on the 3D opal face.
   */
  builderMappedImageIndex?: number | null;
  /**
   * Image hash last processed by automatic crop analysis.
   */
  builderMappingAnalyzedImageHash?: string | null;
  builderPhotoAnalysisVersion?: number | null;
  /**
   * Confidence that automatic analysis isolated one opal face.
   */
  builderPhotoAnalysisConfidence?: number | null;
  /**
   * Last automatic image-analysis failure. Empty after a successful run.
   */
  builderMappingAnalysisError?: string | null;
  /**
   * Approved normalized 96-sample stone boundary. Automatic analysis never overwrites reviewed or manual values.
   */
  builderContour?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Latest automatic contour candidate awaiting visual review.
   */
  builderContourCandidate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * SHA-256 of the source bytes used by the approved contour.
   */
  builderContourSourceImageHash?: string | null;
  /**
   * Candidate crop horizontal focus.
   */
  builderPhotoCandidateFocalX?: number | null;
  /**
   * Candidate crop vertical focus.
   */
  builderPhotoCandidateFocalY?: number | null;
  /**
   * Candidate crop zoom.
   */
  builderPhotoCandidateZoom?: number | null;
  /**
   * Candidate crop rotation in degrees.
   */
  builderPhotoCandidateRotation?: number | null;
  /**
   * Set when mapping is explicitly approved as Reviewed or Manual.
   */
  builderMappingReviewedAt?: string | null;
  /**
   * Internal review notes, image caveats, and reasons for manual overrides.
   */
  builderMappingNotes?: string | null;
  /**
   * Show this loose opal in the custom ring builder. Requires Reviewed or Manual mapping and complete visual fields.
   */
  builderEligible?: boolean | null;
  builderSilhouette?: ('oval' | 'round' | 'elongated' | 'cushion' | 'pear' | 'heart') | null;
  builderRecommendedStyle?: ('gemini' | 'coral' | 'sun-moon' | 'aurora') | null;
  /**
   * Six-digit hex body tone
   */
  builderBodyColour?: string | null;
  /**
   * Primary play-of-colour hex
   */
  builderFlashColourPrimary?: string | null;
  /**
   * Secondary play-of-colour hex
   */
  builderFlashColourSecondary?: string | null;
  /**
   * Accent play-of-colour hex
   */
  builderFlashColourAccent?: string | null;
  /**
   * 0 opaque, 1 transparent
   */
  builderTransmission?: number | null;
  /**
   * Horizontal focal point, 0 to 1
   */
  builderPhotoFocalX?: number | null;
  /**
   * Vertical focal point, 0 to 1
   */
  builderPhotoFocalY?: number | null;
  /**
   * Crop zoom, 1 or greater
   */
  builderPhotoZoom?: number | null;
  /**
   * Base image rotation used before customer adjustments
   */
  builderPhotoRotation?: number | null;
  /**
   * Ring size (if applicable)
   */
  ringSize?: string | null;
  /**
   * Care and maintenance instructions
   */
  careInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Comes with certificate of authenticity
   */
  certified?: boolean | null;
  /**
   * Certificate of authenticity number
   */
  certificateNumber?: string | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders with payment and shipping details
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order identifier (e.g., OPAL-ABC123)
   */
  orderNumber: string;
  /**
   * Order source system
   */
  source: string;
  /**
   * Original WooCommerce order ID
   */
  legacyWooId?: number | null;
  legacyWooStatus?: string | null;
  orderPlacedAt?: string | null;
  paidAt?: string | null;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded' | 'disputed';
  customer: {
    email: string;
    name: string;
    phone?: string | null;
  };
  shippingAddress: {
    line1: string;
    line2?: string | null;
    city: string;
    state?: string | null;
    postalCode?: string | null;
    country: string;
  };
  billingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  items: {
    productId: string;
    slug: string;
    name: string;
    price: number;
    quantity: number;
    image?: string | null;
    id?: string | null;
  }[];
  /**
   * Sum of item prices before shipping and tax
   */
  subtotal: number;
  shipping?: number | null;
  tax?: number | null;
  /**
   * Final order total including shipping and tax
   */
  total: number;
  currency?: string | null;
  /**
   * Stripe Checkout Session ID
   */
  stripeSessionId: string;
  /**
   * Stock reservation consumed by this Stripe order
   */
  inventoryReservation?: (number | null) | InventoryReservation;
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  /**
   * Cumulative Stripe refund in currency minor units (cents for AUD)
   */
  stripeRefundedAmount?: number | null;
  stripeDisputeId?: string | null;
  stripeDisputeStatus?: string | null;
  /**
   * Order status restored when a Stripe dispute is won
   */
  statusBeforeDispute?: string | null;
  paymentMethod?: string | null;
  legacyTransactionId?: string | null;
  /**
   * WooCommerce refund audit data
   */
  legacyRefunds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confirmationEmailSentAt?: string | null;
  confirmationEmailError?: string | null;
  inventoryRestockedAt?: string | null;
  inventoryDecrementedAt?: string | null;
  inventoryAlertSentAt?: string | null;
  inventoryAlertError?: string | null;
  shipmentEmailSentAt?: string | null;
  /**
   * Last dispatch-email error. Saving a shipped order with tracking retries delivery.
   */
  shipmentEmailError?: string | null;
  /**
   * Shipping carrier tracking number
   */
  trackingNumber?: string | null;
  shippingCarrier?: ('australia-post' | 'startrack' | 'dhl' | 'fedex' | 'other') | null;
  /**
   * Internal notes about this order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Short-lived stock holds created before redirecting a customer to Stripe
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-reservations".
 */
export interface InventoryReservation {
  id: number;
  token: string;
  stripeSessionId: string;
  status: 'active' | 'pending-payment' | 'consumed' | 'released';
  expiresAt: string;
  releasedAt?: string | null;
  releaseReason?: string | null;
  consumedAt?: string | null;
  items: {
    productId: string;
    slug: string;
    name: string;
    unitAmountCents: number;
    quantity: number;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer database for CRM and marketing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  /**
   * Original WooCommerce customer ID
   */
  legacyWooId?: number | null;
  wooCreatedAt?: string | null;
  name?: string | null;
  phone?: string | null;
  /**
   * Has opted in to receive marketing emails
   */
  subscribedToNewsletter?: boolean | null;
  /**
   * Email address has been verified
   */
  emailVerified?: boolean | null;
  /**
   * Date when customer subscribed to newsletter
   */
  subscribedAt?: string | null;
  confirmationTokenHash?: string | null;
  confirmationExpiresAt?: string | null;
  unsubscribeTokenHash?: string | null;
  newsletterWelcomeSentAt?: string | null;
  newsletterEmailError?: string | null;
  /**
   * How this customer was acquired
   */
  source?: ('checkout' | 'newsletter' | 'contact' | 'manual' | 'import') | null;
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  /**
   * Total number of orders placed
   */
  totalOrders?: number | null;
  /**
   * Total amount spent (AUD)
   */
  totalSpent?: number | null;
  /**
   * Date of most recent order
   */
  lastOrderDate?: string | null;
  /**
   * Default shipping address (from most recent order)
   */
  defaultAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Tags for customer segmentation and marketing
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Website enquiries, custom design leads, and course interest
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  reference: string;
  type:
    | 'general'
    | 'custom-design'
    | 'virtual-viewing'
    | 'product-question'
    | 'order-support'
    | 'returns'
    | 'wholesale'
    | 'course-interest';
  status:
    | 'new'
    | 'reviewing'
    | 'awaiting-customer'
    | 'consultation'
    | 'quoted'
    | 'accepted'
    | 'deposit-paid'
    | 'in-production'
    | 'completed'
    | 'declined'
    | 'spam';
  name: string;
  email: string;
  phone?: string | null;
  orderNumber?: string | null;
  product?: string | null;
  budget?: string | null;
  timeline?: string | null;
  message: string;
  /**
   * Validated custom builder configuration snapshot
   */
  designConfiguration?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  source: 'website-contact' | 'custom-builder' | 'manual';
  submittedAt: string;
  ownerEmailSentAt?: string | null;
  customerEmailSentAt?: string | null;
  emailDeliveryError?: string | null;
  /**
   * Private staff notes
   */
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Public course and lesson outlines plus interest-enquiry status. Lesson bodies, enrolments, and payments are not managed here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  /**
   * Stable LearnDash course ID when imported
   */
  legacyWordPressId?: number | null;
  title: string;
  /**
   * Permanent public URL identifier
   */
  slug: string;
  summary: string;
  /**
   * Public overview only. Do not imply confirmed lessons, dates, live support, bookings, or paid availability.
   */
  introduction: string;
  featuredImage?: (number | null) | Media;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  format: 'online' | 'live-online' | 'in-person';
  level: 'beginner' | 'all-levels' | 'intermediate';
  duration?: string | null;
  availability: 'register-interest' | 'coming-soon' | 'closed';
  instructor: {
    name: string;
    role?: string | null;
    bio?: string | null;
  };
  curriculum: {
    title: string;
    summary: string;
    /**
     * Start each lesson with ## Lesson title, then add one public step per line. Do not paste private lesson content here.
     */
    topics?: string | null;
    id?: string | null;
  }[];
  audience?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  outcomes?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  tenantId: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable ledger preventing a WooCommerce cutover import from running twice
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-import-runs".
 */
export interface CommerceImportRun {
  id: number;
  runId: string;
  mode: 'initial' | 'final-delta';
  status: 'running' | 'completed' | 'failed';
  deploymentId?: string | null;
  startedAt: string;
  completedAt?: string | null;
  failedAt?: string | null;
  summary?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  error?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Revisioned custom jewellery quotes; amounts are stored in currency cents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-quotes".
 */
export interface CustomQuote {
  id: number;
  quoteNumber: string;
  quoteSeriesId: string;
  revision: number;
  /**
   * Select an earlier quote to create its next immutable revision
   */
  supersedes?: (number | null) | CustomQuote;
  enquiry: number | Enquiry;
  customerEmail: string;
  /**
   * Use “Send / retry quote” to deliver a draft; Sent cannot be forged manually.
   */
  status: 'draft' | 'sent' | 'accepted' | 'expired' | 'cancelled' | 'superseded';
  /**
   * Full quoted price in cents
   */
  amountCents: number;
  /**
   * Required deposit in cents; zero means no deposit
   */
  depositAmountCents: number;
  currency: 'AUD';
  validUntil: string;
  /**
   * Exact scope, materials, timing, inclusions, exclusions, and cancellation terms accepted for this revision
   */
  terms: string;
  acceptedAt?: string | null;
  acceptedByEmail?: string | null;
  acceptedTermsHash?: string | null;
  acceptedStatementVersion?: string | null;
  acceptedEvidenceHash?: string | null;
  depositStatus: 'not-required' | 'awaiting-payment' | 'paid' | 'refunded';
  amountPaidCents?: number | null;
  paidAt?: string | null;
  stripeRefundedAmountCents?: number | null;
  refundedAt?: string | null;
  depositCheckoutGeneration?: number | null;
  pendingStripeCheckoutSessionId?: string | null;
  pendingStripeCheckoutExpiresAt?: string | null;
  stripeCheckoutSessionId?: string | null;
  stripePaymentIntentId?: string | null;
  stripeDisputeId?: string | null;
  stripeDisputeStatus?: string | null;
  depositDisputedAt?: string | null;
  stripeDisputeEventAt?: string | null;
  /**
   * Private operational notes; not part of accepted terms
   */
  internalNotes?: string | null;
  linkVersion: number;
  customerEmailSentAt?: string | null;
  customerEmailProviderId?: string | null;
  customerEmailError?: string | null;
  deliveryStatus: 'not-sent' | 'issuing' | 'sent' | 'failed';
  deliveryAttemptCount?: number | null;
  deliveryLastAttemptAt?: string | null;
  depositConfirmationEmailSentAt?: string | null;
  depositConfirmationEmailProviderId?: string | null;
  depositConfirmationEmailError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Append-only evidence ledger for custom quote lifecycle changes
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-quote-events".
 */
export interface CustomQuoteEvent {
  id: number;
  quote: number | CustomQuote;
  enquiry: number | Enquiry;
  eventType:
    | 'created'
    | 'sent'
    | 'accepted'
    | 'expired'
    | 'cancelled'
    | 'superseded'
    | 'deposit-paid'
    | 'deposit-refunded'
    | 'deposit-disputed'
    | 'deposit-dispute-resolved';
  occurredAt: string;
  quoteRevision: number;
  actorType: 'admin' | 'customer' | 'stripe' | 'system';
  actorEmail?: string | null;
  amountCents: number;
  depositAmountCents: number;
  currency: string;
  validUntil: string;
  termsSnapshot: string;
  termsHash: string;
  evidence?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Physical reference evidence and maker approval for each ring-builder design.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ring-designs".
 */
export interface RingDesign {
  id: number;
  name: string;
  slug: string;
  style: 'gemini' | 'coral' | 'sun-moon' | 'aurora';
  status: 'draft' | 'published' | 'archived';
  /**
   * Versioned source records: assetPath, sourceType, view, productSlug/sourceUrl, observedAt, and notes.
   */
  sourceReferences:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Caliper, photogrammetry, or maker-drawing measurements in millimetres. Required before approval.
   */
  measurements?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Model source, version, optional asset URL, and notes. Procedural constants alone remain draft evidence.
   */
  modelDefinition?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Confirms the rendered construction matches the physical master.
   */
  makerApproved?: boolean | null;
  approvedAt?: string | null;
  /**
   * Name the physical master, remaining tolerances, and who approved it.
   */
  approvalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'commerce-import-runs';
        value: number | CommerceImportRun;
      } | null)
    | ({
        relationTo: 'inventory-reservations';
        value: number | InventoryReservation;
      } | null)
    | ({
        relationTo: 'custom-quotes';
        value: number | CustomQuote;
      } | null)
    | ({
        relationTo: 'custom-quote-events';
        value: number | CustomQuoteEvent;
      } | null)
    | ({
        relationTo: 'ring-designs';
        value: number | RingDesign;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  legacySourceUrl?: T;
  alt?: T;
  caption?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  name?: T;
  slug?: T;
  bio?: T;
  avatar?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  name?: T;
  slug?: T;
  description?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  name?: T;
  slug?: T;
  description?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  tags?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  tenantId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  featured?: T;
  stock?: T;
  sku?: T;
  legacyWooId?: T;
  wooStatus?: T;
  wooCatalogVisibility?: T;
  wooManageStock?: T;
  wooModifiedAt?: T;
  material?: T;
  stoneType?: T;
  stoneOrigin?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        depth?: T;
      };
  weight?: T;
  weightUnit?: T;
  builderMappingStatus?: T;
  builderMappingConfidence?: T;
  builderMappingVersion?: T;
  builderMappingMode?: T;
  builderMappingSourceImageHash?: T;
  builderMappingInputHash?: T;
  builderMappedImageIndex?: T;
  builderMappingAnalyzedImageHash?: T;
  builderPhotoAnalysisVersion?: T;
  builderPhotoAnalysisConfidence?: T;
  builderMappingAnalysisError?: T;
  builderContour?: T;
  builderContourCandidate?: T;
  builderContourSourceImageHash?: T;
  builderPhotoCandidateFocalX?: T;
  builderPhotoCandidateFocalY?: T;
  builderPhotoCandidateZoom?: T;
  builderPhotoCandidateRotation?: T;
  builderMappingReviewedAt?: T;
  builderMappingNotes?: T;
  builderEligible?: T;
  builderSilhouette?: T;
  builderRecommendedStyle?: T;
  builderBodyColour?: T;
  builderFlashColourPrimary?: T;
  builderFlashColourSecondary?: T;
  builderFlashColourAccent?: T;
  builderTransmission?: T;
  builderPhotoFocalX?: T;
  builderPhotoFocalY?: T;
  builderPhotoZoom?: T;
  builderPhotoRotation?: T;
  ringSize?: T;
  careInstructions?: T;
  certified?: T;
  certificateNumber?: T;
  tenantId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  source?: T;
  legacyWooId?: T;
  legacyWooStatus?: T;
  orderPlacedAt?: T;
  paidAt?: T;
  status?: T;
  customer?:
    | T
    | {
        email?: T;
        name?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  items?:
    | T
    | {
        productId?: T;
        slug?: T;
        name?: T;
        price?: T;
        quantity?: T;
        image?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  tax?: T;
  total?: T;
  currency?: T;
  stripeSessionId?: T;
  inventoryReservation?: T;
  stripePaymentIntentId?: T;
  stripeRefundedAmount?: T;
  stripeDisputeId?: T;
  stripeDisputeStatus?: T;
  statusBeforeDispute?: T;
  paymentMethod?: T;
  legacyTransactionId?: T;
  legacyRefunds?: T;
  confirmationEmailSentAt?: T;
  confirmationEmailError?: T;
  inventoryRestockedAt?: T;
  inventoryDecrementedAt?: T;
  inventoryAlertSentAt?: T;
  inventoryAlertError?: T;
  shipmentEmailSentAt?: T;
  shipmentEmailError?: T;
  trackingNumber?: T;
  shippingCarrier?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  legacyWooId?: T;
  wooCreatedAt?: T;
  name?: T;
  phone?: T;
  subscribedToNewsletter?: T;
  emailVerified?: T;
  subscribedAt?: T;
  confirmationTokenHash?: T;
  confirmationExpiresAt?: T;
  unsubscribeTokenHash?: T;
  newsletterWelcomeSentAt?: T;
  newsletterEmailError?: T;
  source?: T;
  notes?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderDate?: T;
  defaultAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  reference?: T;
  type?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  orderNumber?: T;
  product?: T;
  budget?: T;
  timeline?: T;
  message?: T;
  designConfiguration?: T;
  source?: T;
  submittedAt?: T;
  ownerEmailSentAt?: T;
  customerEmailSentAt?: T;
  emailDeliveryError?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  title?: T;
  slug?: T;
  summary?: T;
  introduction?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  format?: T;
  level?: T;
  duration?: T;
  availability?: T;
  instructor?:
    | T
    | {
        name?: T;
        role?: T;
        bio?: T;
      };
  curriculum?:
    | T
    | {
        title?: T;
        summary?: T;
        topics?: T;
        id?: T;
      };
  audience?:
    | T
    | {
        item?: T;
        id?: T;
      };
  outcomes?:
    | T
    | {
        item?: T;
        id?: T;
      };
  tenantId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "commerce-import-runs_select".
 */
export interface CommerceImportRunsSelect<T extends boolean = true> {
  runId?: T;
  mode?: T;
  status?: T;
  deploymentId?: T;
  startedAt?: T;
  completedAt?: T;
  failedAt?: T;
  summary?: T;
  error?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inventory-reservations_select".
 */
export interface InventoryReservationsSelect<T extends boolean = true> {
  token?: T;
  stripeSessionId?: T;
  status?: T;
  expiresAt?: T;
  releasedAt?: T;
  releaseReason?: T;
  consumedAt?: T;
  items?:
    | T
    | {
        productId?: T;
        slug?: T;
        name?: T;
        unitAmountCents?: T;
        quantity?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-quotes_select".
 */
export interface CustomQuotesSelect<T extends boolean = true> {
  quoteNumber?: T;
  quoteSeriesId?: T;
  revision?: T;
  supersedes?: T;
  enquiry?: T;
  customerEmail?: T;
  status?: T;
  amountCents?: T;
  depositAmountCents?: T;
  currency?: T;
  validUntil?: T;
  terms?: T;
  acceptedAt?: T;
  acceptedByEmail?: T;
  acceptedTermsHash?: T;
  acceptedStatementVersion?: T;
  acceptedEvidenceHash?: T;
  depositStatus?: T;
  amountPaidCents?: T;
  paidAt?: T;
  stripeRefundedAmountCents?: T;
  refundedAt?: T;
  depositCheckoutGeneration?: T;
  pendingStripeCheckoutSessionId?: T;
  pendingStripeCheckoutExpiresAt?: T;
  stripeCheckoutSessionId?: T;
  stripePaymentIntentId?: T;
  stripeDisputeId?: T;
  stripeDisputeStatus?: T;
  depositDisputedAt?: T;
  stripeDisputeEventAt?: T;
  internalNotes?: T;
  linkVersion?: T;
  customerEmailSentAt?: T;
  customerEmailProviderId?: T;
  customerEmailError?: T;
  deliveryStatus?: T;
  deliveryAttemptCount?: T;
  deliveryLastAttemptAt?: T;
  depositConfirmationEmailSentAt?: T;
  depositConfirmationEmailProviderId?: T;
  depositConfirmationEmailError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-quote-events_select".
 */
export interface CustomQuoteEventsSelect<T extends boolean = true> {
  quote?: T;
  enquiry?: T;
  eventType?: T;
  occurredAt?: T;
  quoteRevision?: T;
  actorType?: T;
  actorEmail?: T;
  amountCents?: T;
  depositAmountCents?: T;
  currency?: T;
  validUntil?: T;
  termsSnapshot?: T;
  termsHash?: T;
  evidence?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ring-designs_select".
 */
export interface RingDesignsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  style?: T;
  status?: T;
  sourceReferences?: T;
  measurements?: T;
  modelDefinition?: T;
  makerApproved?: T;
  approvedAt?: T;
  approvalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}