/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    categories: Category;
    products: Product;
    orders: Order;
    customers: Customer;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'user';
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Stable attachment ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  /**
   * Original URL for a safely imported legacy asset
   */
  legacySourceUrl?: string | null;
  alt: string;
  caption?: string | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  /**
   * Stable post ID imported from the legacy WordPress site
   */
  legacyWordPressId?: number | null;
  title: string;
  /**
   * URL-friendly identifier
   */
  slug: string;
  /**
   * Short summary of the post
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  status: 'draft' | 'published' | 'archived';
  /**
   * When this post was published
   */
  publishedAt?: string | null;
  author?: (number | null) | User;
  categories?: (number | Category)[] | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    keywords?: string[] | null;
    ogImage?: (number | null) | Media;
  };
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  description?: string | null;
  /**
   * Number of posts in this category
   */
  postCount?: number | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  price: number;
  /**
   * Original price (for showing discounts)
   */
  compareAtPrice?: number | null;
  images?:
    | {
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  category: 'opal-rings' | 'opal-necklaces' | 'opal-earrings' | 'opal-bracelets' | 'raw-opals' | 'custom-commissions';
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  status: 'draft' | 'published' | 'archived';
  featured?: boolean | null;
  /**
   * Available quantity (0 = out of stock)
   */
  stock?: number | null;
  /**
   * Stock Keeping Unit (unique identifier)
   */
  sku?: string | null;
  /**
   * Original WooCommerce product ID
   */
  legacyWooId?: number | null;
  /**
   * Original WooCommerce product status
   */
  wooStatus?: string | null;
  wooCatalogVisibility?: string | null;
  wooManageStock?: boolean | null;
  wooModifiedAt?: string | null;
  /**
   * Metal type used in the jewelry
   */
  material?: ('sterling-silver' | '14k-gold' | '18k-gold' | 'white-gold' | 'rose-gold' | 'platinum' | 'none') | null;
  /**
   * Type of opal used
   */
  stoneType?:
    | ('black-opal' | 'white-opal' | 'boulder-opal' | 'crystal-opal' | 'fire-opal' | 'matrix-opal' | 'opal-doublet')
    | null;
  /**
   * Australian mine location where opal was sourced
   */
  stoneOrigin?:
    | ('lightning-ridge' | 'coober-pedy' | 'mintabie' | 'andamooka' | 'queensland' | 'other-australian')
    | null;
  dimensions?: {
    /**
     * Length in mm
     */
    length?: number | null;
    /**
     * Width in mm
     */
    width?: number | null;
    /**
     * Depth/height in mm
     */
    depth?: number | null;
  };
  /**
   * Weight in carats (for opals) or grams (for jewelry)
   */
  weight?: number | null;
  /**
   * Ring size (if applicable)
   */
  ringSize?: string | null;
  /**
   * Care and maintenance instructions
   */
  careInstructions?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Comes with certificate of authenticity
   */
  certified?: boolean | null;
  /**
   * Certificate of authenticity number
   */
  certificateNumber?: string | null;
  /**
   * Associated tenant ID for multi-tenancy
   */
  tenantId: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer orders with payment and shipping details
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Unique order identifier (e.g., OPAL-ABC123)
   */
  orderNumber: string;
  /**
   * Order source system
   */
  source: string;
  /**
   * Original WooCommerce order ID
   */
  legacyWooId?: number | null;
  legacyWooStatus?: string | null;
  orderPlacedAt?: string | null;
  paidAt?: string | null;
  status: 'pending' | 'processing' | 'shipped' | 'delivered' | 'cancelled' | 'refunded' | 'disputed';
  customer: {
    email: string;
    name: string;
    phone?: string | null;
  };
  shippingAddress: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    postalCode: string;
    country: string;
  };
  billingAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  items: {
    productId: string;
    slug: string;
    name: string;
    price: number;
    quantity: number;
    image?: string | null;
    id?: string | null;
  }[];
  /**
   * Sum of item prices before shipping and tax
   */
  subtotal: number;
  shipping?: number | null;
  tax?: number | null;
  /**
   * Final order total including shipping and tax
   */
  total: number;
  currency?: string | null;
  /**
   * Stripe Checkout Session ID
   */
  stripeSessionId: string;
  /**
   * Stripe Payment Intent ID
   */
  stripePaymentIntentId?: string | null;
  paymentMethod?: string | null;
  legacyTransactionId?: string | null;
  /**
   * WooCommerce refund audit data
   */
  legacyRefunds?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  confirmationEmailSentAt?: string | null;
  confirmationEmailError?: string | null;
  inventoryRestockedAt?: string | null;
  inventoryDecrementedAt?: string | null;
  inventoryAlertSentAt?: string | null;
  inventoryAlertError?: string | null;
  /**
   * Shipping carrier tracking number
   */
  trackingNumber?: string | null;
  shippingCarrier?: ('australia-post' | 'startrack' | 'dhl' | 'fedex' | 'other') | null;
  /**
   * Internal notes about this order
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Customer database for CRM and marketing
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: number;
  email: string;
  /**
   * Original WooCommerce customer ID
   */
  legacyWooId?: number | null;
  wooCreatedAt?: string | null;
  name?: string | null;
  phone?: string | null;
  /**
   * Has opted in to receive marketing emails
   */
  subscribedToNewsletter?: boolean | null;
  /**
   * Email address has been verified
   */
  emailVerified?: boolean | null;
  /**
   * Date when customer subscribed to newsletter
   */
  subscribedAt?: string | null;
  confirmationTokenHash?: string | null;
  confirmationExpiresAt?: string | null;
  unsubscribeTokenHash?: string | null;
  newsletterWelcomeSentAt?: string | null;
  newsletterEmailError?: string | null;
  /**
   * How this customer was acquired
   */
  source?: ('checkout' | 'newsletter' | 'contact' | 'manual' | 'import') | null;
  /**
   * Internal notes about this customer
   */
  notes?: string | null;
  /**
   * Total number of orders placed
   */
  totalOrders?: number | null;
  /**
   * Total amount spent (AUD)
   */
  totalSpent?: number | null;
  /**
   * Date of most recent order
   */
  lastOrderDate?: string | null;
  /**
   * Default shipping address (from most recent order)
   */
  defaultAddress?: {
    line1?: string | null;
    line2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  /**
   * Tags for customer segmentation and marketing
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'customers';
        value: number | Customer;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  legacySourceUrl?: T;
  alt?: T;
  caption?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  legacyWordPressId?: T;
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        keywords?: T;
        ogImage?: T;
      };
  tenantId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  postCount?: T;
  tenantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  compareAtPrice?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  category?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  status?: T;
  featured?: T;
  stock?: T;
  sku?: T;
  legacyWooId?: T;
  wooStatus?: T;
  wooCatalogVisibility?: T;
  wooManageStock?: T;
  wooModifiedAt?: T;
  material?: T;
  stoneType?: T;
  stoneOrigin?: T;
  dimensions?:
    | T
    | {
        length?: T;
        width?: T;
        depth?: T;
      };
  weight?: T;
  ringSize?: T;
  careInstructions?: T;
  certified?: T;
  certificateNumber?: T;
  tenantId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  source?: T;
  legacyWooId?: T;
  legacyWooStatus?: T;
  orderPlacedAt?: T;
  paidAt?: T;
  status?: T;
  customer?:
    | T
    | {
        email?: T;
        name?: T;
        phone?: T;
      };
  shippingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  billingAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  items?:
    | T
    | {
        productId?: T;
        slug?: T;
        name?: T;
        price?: T;
        quantity?: T;
        image?: T;
        id?: T;
      };
  subtotal?: T;
  shipping?: T;
  tax?: T;
  total?: T;
  currency?: T;
  stripeSessionId?: T;
  stripePaymentIntentId?: T;
  paymentMethod?: T;
  legacyTransactionId?: T;
  legacyRefunds?: T;
  confirmationEmailSentAt?: T;
  confirmationEmailError?: T;
  inventoryRestockedAt?: T;
  inventoryDecrementedAt?: T;
  inventoryAlertSentAt?: T;
  inventoryAlertError?: T;
  trackingNumber?: T;
  shippingCarrier?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  email?: T;
  legacyWooId?: T;
  wooCreatedAt?: T;
  name?: T;
  phone?: T;
  subscribedToNewsletter?: T;
  emailVerified?: T;
  subscribedAt?: T;
  confirmationTokenHash?: T;
  confirmationExpiresAt?: T;
  unsubscribeTokenHash?: T;
  newsletterWelcomeSentAt?: T;
  newsletterEmailError?: T;
  source?: T;
  notes?: T;
  totalOrders?: T;
  totalSpent?: T;
  lastOrderDate?: T;
  defaultAddress?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
      };
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}