import type { CollectionConfig } from 'payload'
import { isAdmin } from '../../lib/payload-access.ts'

export const Enquiries: CollectionConfig = {
  slug: 'enquiries',
  defaultSort: '-submittedAt',
  admin: {
    useAsTitle: 'reference',
    defaultColumns: ['reference', 'type', 'status', 'name', 'email', 'submittedAt'],
    group: 'CRM',
    description: 'Website enquiries and custom design leads',
  },
  access: {
    read: isAdmin,
    create: isAdmin,
    update: isAdmin,
    delete: isAdmin,
  },
  fields: [
    {
      name: 'reference',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: { readOnly: true },
    },
    {
      name: 'type',
      type: 'select',
      required: true,
      options: [
        { label: 'General question', value: 'general' },
        { label: 'Custom jewellery', value: 'custom-design' },
        { label: 'Product viewing', value: 'virtual-viewing' },
        { label: 'Product question', value: 'product-question' },
        { label: 'Order support', value: 'order-support' },
        { label: 'Return or exchange', value: 'returns' },
        { label: 'Wholesale or trade', value: 'wholesale' },
      ],
    },
    {
      name: 'status',
      type: 'select',
      required: true,
      defaultValue: 'new',
      options: [
        { label: 'New', value: 'new' },
        { label: 'Reviewing', value: 'reviewing' },
        { label: 'Awaiting customer', value: 'awaiting-customer' },
        { label: 'Consultation', value: 'consultation' },
        { label: 'Quoted', value: 'quoted' },
        { label: 'Accepted', value: 'accepted' },
        { label: 'Deposit paid', value: 'deposit-paid' },
        { label: 'In production', value: 'in-production' },
        { label: 'Completed', value: 'completed' },
        { label: 'Declined', value: 'declined' },
        { label: 'Spam', value: 'spam' },
      ],
      admin: { position: 'sidebar' },
    },
    { name: 'name', type: 'text', required: true },
    { name: 'email', type: 'email', required: true, index: true },
    { name: 'phone', type: 'text' },
    { name: 'orderNumber', type: 'text' },
    { name: 'product', type: 'text' },
    { name: 'budget', type: 'text' },
    { name: 'timeline', type: 'text' },
    { name: 'message', type: 'textarea', required: true },
    {
      name: 'designConfiguration',
      type: 'json',
      admin: { description: 'Validated custom builder configuration snapshot' },
    },
    {
      name: 'source',
      type: 'select',
      required: true,
      defaultValue: 'website-contact',
      options: [
        { label: 'Website contact', value: 'website-contact' },
        { label: 'Custom builder', value: 'custom-builder' },
        { label: 'Manual', value: 'manual' },
      ],
      admin: { position: 'sidebar' },
    },
    {
      name: 'submittedAt',
      type: 'date',
      required: true,
      admin: { readOnly: true, position: 'sidebar' },
    },
    { name: 'ownerEmailSentAt', type: 'date', admin: { readOnly: true, position: 'sidebar' } },
    { name: 'customerEmailSentAt', type: 'date', admin: { readOnly: true, position: 'sidebar' } },
    { name: 'emailDeliveryError', type: 'textarea', admin: { readOnly: true } },
    { name: 'internalNotes', type: 'textarea', admin: { description: 'Private staff notes' } },
  ],
}
